sonar.projectKey=genzouw_trim-text
sonar.organization=genzouw
sonar.host.url=https://sonarcloud.io

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=trim-text

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=.
sonar.shell.file.suffixes=.sh,.bash,.ksh,.zsh,

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude test directories and coverage files if any
sonar.exclusions=**/*.test.*,**/*.spec.*,coverage/**,.github/**,.coderabbit.yaml,.pr_agent.toml,sonar-project.properties
